version: '3.8'

services:
  php:
    container_name: php_container
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis

  nginx:
    container_name: nginx_container
    image: nginx:1.15.6
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    container_name: db_container
    image: mariadb:10.4.13
    environment:
      MYSQL_DATABASE: local_jikkyoplay_com
      MYSQL_USER: user
      MYSQL_PASSWORD: passuser
      MYSQL_ROOT_PASSWORD: passroot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    container_name: redis_container
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    command: redis-server --appendonly yes

volumes:
  mysql-data: